---
- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart smb
  service:
    name: smbd
    state: restarted
